### ISSUE TITLE
[BUG] שיתוף התוכנית

### ISSUE THREAD

**Issue by arirkts369** [Tovli/Mazilon#4]
**Describe the Bug**

**To Reproduce**
1. Go to 'התכנית שלי'
2. Click on ' the share button'
3. Press  'שגרה או חרום'
4. Choose whatsapp contact to send to.
5. Error: In the message there is no תוכנית אישית attached.

**Expected Behavior**
Attach   תוכנית אישית to the message sent to recipent.

**Screenshots**

**Environment (please complete the following information):**
- Browser (if applicable) [e.g. chrome, safari]

**Additional Context**

**Comment by Tovli** [comment]
Thanks @arirkts369 
Can you please indicate which device did you use? - what is the android version and what model is your device?

**Comment by arirkts369** [comment]
hi I used xiaomi13c and  android version 13 TP1A.220624.014.
